cmr:
  image: inspectit/cmr:latest
  ports:
   - "8182:8182"
  volumes:
   - ./environments:/CMR/custom/environments
   - ./profiles:/CMR/custom/profiles
dvdstore:
  image: inspectit/dvdstore
  links:
   - cmr
  ports:
   - "8080:8080"
  environment:
   - AGENT_NAME=dvdstore
   - INSPECTIT_CMR_WAIT=60
gui:
  image: inspectit/inspectit:latest
  environment:
   - DISPLAY
   - XAUTHORITY=/.Xauth
  net: "host"
  volumes:
   - ${XAUTHORITY}:/.Xauth
